
#
# This file has been modified by the Webis Group 
# to fit the needs of the IR Anthology. 
# The original is part of the ACL Anthology. 
#
title = "IR Anthology"
disablePathToLower = true
staticDir = ["static", "data-export"]

[permalinks]
  papers = "/:filename/"
[params]
  githash = "136d490d0e812453b4d151fde8a3dcc2416ca718"
  githashshort = "136d490d"
  timestamp = "24 October 2021 at 21:29 UTC"
